Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -20,21 +20,21 @@ runs:
 
     - shell: bash
       run: |
-        docker pull ghcr.io/alexbelgium/builder/amd64-builder:${{ steps.version.outputs.version }}
-    - shell: bash
-      run: |
-        for j in {1..15}; do
-          if CAS_API_KEY= cas authenticate --silent --signerID notary@alexbelgium/builder.io docker://ghcr.io/alexbelgium/builder/amd64-builder:${{ steps.version.outputs.version }}; then
-            exit 0
-          fi
-          sleep $((5 * j))
-        done
-        echo "Invalid signature!"
-        exit 1
+        docker pull ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}
+  #  - shell: bash
+  #    run: |
+  #      for j in {1..15}; do
+  #        if CAS_API_KEY= cas authenticate --silent --signerID notary@alexbelgium/builder.io docker://ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }}; then
+  #          exit 0
+  #        fi
+  #        sleep $((5 * j))
+  #      done
+  #      echo "Invalid signature!"
+  #      exit 1
     - shell: bash
       id: builder
       run: |
-        builder=$(docker images ghcr.io/alexbelgium/builder/amd64-builder:${{ steps.version.outputs.version }} -q)
+        builder=$(docker images ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }} -q)
         echo "::set-output name=id::$builder"
     - shell: bash
       id: build
@@ -46,7 +46,7 @@ runs:
             -v ~/.docker:/root/.docker \
             -v ${{ github.workspace }}:/data \
             --env-file "${{ github.action_path }}/env_file" \
-            ghcr.io/alexbelgium/builder/amd64-builder:${{ steps.version.outputs.version }} \
+            ghcr.io/home-assistant/amd64-builder:${{ steps.version.outputs.version }} \
             ${{ inputs.args }}
     - shell: bash
       id: verify
